# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_trip_plan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Joinbycurr',
            field=models.BooleanField(default=False),
        ),
    ]
