# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_trip_joinbycurr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Joinbycurr',
            new_name='joinbycurr',
        ),
    ]
